/**
 * Verifies the partial UNIQUE indexes from migration
 * 0019_unique_external_ids (venues_tm_venue_uniq, venues_google_place_uniq,
 * performers_tm_attraction_uniq, performers_musicbrainz_uniq) reject
 * duplicates at the DB level, and that matchOrCreateVenue /
 * matchOrCreatePerformer's catch(isUniqueViolation) branch falls back
 * to the existing row when two concurrent calls race for the same
 * external ID.
 *
 * Run with:
 *   DATABASE_URL=postgresql://showbook:showbook_dev@localhost:5433/showbook_e2e \
 *     pnpm --filter @showbook/api exec node --import tsx --test \
 *     src/__tests__/matcher-unique-race.integration.test.ts
 */

import { describe, it, before, after } from 'node:test';
import assert from 'node:assert/strict';
import { db, performers, venues } from '@showbook/db';
import { eq, sql } from 'drizzle-orm';
import { matchOrCreateVenue, isUniqueViolation } from '../venue-matcher';
import { matchOrCreatePerformer } from '../performer-matcher';
import { withTimeout } from './_test-helpers';

const PREFIX = 'fadbc555';

async function cleanup(): Promise<void> {
  // Test rows are inserted with autogenerated UUIDs, so target by name
  // (which always begins with PREFIX in this file).
  await db.execute(sql`DELETE FROM performers WHERE name LIKE ${PREFIX + '%'}`);
  await db.execute(sql`DELETE FROM venues     WHERE name LIKE ${PREFIX + '%'}`);
}

describe('partial UNIQUE indexes on external IDs', () => {
  before(async () => withTimeout(45_000, cleanup));
  after(async () => withTimeout(45_000, cleanup));

  describe('venues table', () => {
    it('rejects a duplicate ticketmaster_venue_id with code 23505', async () => {
      const tmId = `${PREFIX}-tm-1`;
      await db.insert(venues).values({
        name: `${PREFIX} TM A`,
        city: 'Seattle',
        country: 'US',
        ticketmasterVenueId: tmId,
      });

      let err: unknown;
      try {
        await db.insert(venues).values({
          name: `${PREFIX} TM B`,
          city: 'Boston',
          country: 'US',
          ticketmasterVenueId: tmId,
        });
      } catch (e) {
        err = e;
      }
      assert.ok(err, 'expected duplicate insert to throw');
      assert.ok(
        isUniqueViolation(err),
        'expected unique-violation (23505) on the partial UNIQUE index',
      );
    });

    it('allows multiple rows with NULL ticketmaster_venue_id (partial)', async () => {
      await db.insert(venues).values({
        name: `${PREFIX} TM Null 1`,
        city: 'NYC',
        country: 'US',
        ticketmasterVenueId: null,
      });
      // Second NULL row must succeed because the index has WHERE … IS NOT NULL.
      await db.insert(venues).values({
        name: `${PREFIX} TM Null 2`,
        city: 'NYC',
        country: 'US',
        ticketmasterVenueId: null,
      });
    });

    it('rejects a duplicate google_place_id with code 23505', async () => {
      const placeId = `${PREFIX}-gp-1`;
      await db.insert(venues).values({
        name: `${PREFIX} GP A`,
        city: 'NYC',
        country: 'US',
        googlePlaceId: placeId,
      });

      let err: unknown;
      try {
        await db.insert(venues).values({
          name: `${PREFIX} GP B`,
          city: 'NYC',
          country: 'US',
          googlePlaceId: placeId,
        });
      } catch (e) {
        err = e;
      }
      assert.ok(
        isUniqueViolation(err),
        'expected unique-violation (23505) on the partial UNIQUE index',
      );
    });
  });

  describe('performers table', () => {
    it('rejects a duplicate ticketmaster_attraction_id with code 23505', async () => {
      const tmId = `${PREFIX}-att-1`;
      await db.insert(performers).values({
        name: `${PREFIX} Att A`,
        ticketmasterAttractionId: tmId,
      });

      let err: unknown;
      try {
        await db.insert(performers).values({
          name: `${PREFIX} Att B`,
          ticketmasterAttractionId: tmId,
        });
      } catch (e) {
        err = e;
      }
      assert.ok(
        isUniqueViolation(err),
        'expected unique-violation (23505) on the partial UNIQUE index',
      );
    });

    it('rejects a duplicate musicbrainz_id with code 23505', async () => {
      const mbid = `${PREFIX}-mb-1`;
      await db.insert(performers).values({
        name: `${PREFIX} MB A`,
        musicbrainzId: mbid,
      });

      let err: unknown;
      try {
        await db.insert(performers).values({
          name: `${PREFIX} MB B`,
          musicbrainzId: mbid,
        });
      } catch (e) {
        err = e;
      }
      assert.ok(
        isUniqueViolation(err),
        'expected unique-violation (23505) on the partial UNIQUE index',
      );
    });
  });

  describe('matchOrCreateVenue under concurrent race', () => {
    it('two parallel calls with the same tmVenueId converge on a single row', async () => {
      // Different name+city → different advisory-lock keys, so neither
      // call blocks the other on the lock. Both pass step 1 (SELECT by
      // tmVenueId) before either commits, both reach the transaction.
      // The first INSERT wins; the second gets 23505 from the partial
      // UNIQUE index and falls into the catch(isUniqueViolation) branch.
      const tmId = `${PREFIX}-race-tm`;
      const [a, b] = await Promise.all([
        matchOrCreateVenue({
          name: `${PREFIX} Race A`,
          city: 'Seattle',
          country: 'US',
          tmVenueId: tmId,
          lat: 47.6,
          lng: -122.3,
        }),
        matchOrCreateVenue({
          name: `${PREFIX} Race B`,
          city: 'Boston',
          country: 'US',
          tmVenueId: tmId,
          lat: 42.4,
          lng: -71.1,
        }),
      ]);

      assert.equal(
        a.venue.id,
        b.venue.id,
        'both calls should resolve to the same venue.id',
      );
      assert.equal(a.venue.ticketmasterVenueId, tmId);

      const rows = await db
        .select()
        .from(venues)
        .where(eq(venues.ticketmasterVenueId, tmId));
      assert.equal(rows.length, 1, 'only one venue row persists for the shared tmVenueId');
    });

    it('two parallel calls with the same googlePlaceId converge on a single row', async () => {
      const placeId = `${PREFIX}-race-gp`;
      const [a, b] = await Promise.all([
        matchOrCreateVenue({
          name: `${PREFIX} GP Race A`,
          city: 'Austin',
          country: 'US',
          googlePlaceId: placeId,
          lat: 30.27,
          lng: -97.74,
        }),
        matchOrCreateVenue({
          name: `${PREFIX} GP Race B`,
          city: 'Denver',
          country: 'US',
          googlePlaceId: placeId,
          lat: 39.74,
          lng: -104.99,
        }),
      ]);

      assert.equal(a.venue.id, b.venue.id);
      assert.equal(a.venue.googlePlaceId, placeId);

      const rows = await db
        .select()
        .from(venues)
        .where(eq(venues.googlePlaceId, placeId));
      assert.equal(rows.length, 1);
    });
  });

  describe('matchOrCreatePerformer under concurrent race', () => {
    it('two parallel calls with the same tmAttractionId converge on a single row', async () => {
      const tmId = `${PREFIX}-race-att`;
      const [a, b] = await Promise.all([
        matchOrCreatePerformer({
          name: `${PREFIX} P A`,
          tmAttractionId: tmId,
        }),
        matchOrCreatePerformer({
          name: `${PREFIX} P B`,
          tmAttractionId: tmId,
        }),
      ]);
      assert.equal(a.performer.id, b.performer.id);
      assert.equal(a.performer.ticketmasterAttractionId, tmId);
      const rows = await db
        .select()
        .from(performers)
        .where(eq(performers.ticketmasterAttractionId, tmId));
      assert.equal(rows.length, 1);
    });

    it('two parallel calls with the same musicbrainzId converge on a single row', async () => {
      // Names must not collide with the earlier "rejects a duplicate
      // musicbrainz_id" test (which leaves a `${PREFIX} MB A` row behind):
      // matchOrCreatePerformer matches existing rows case-insensitively by
      // name, so reusing those names would short-circuit step 3 and never
      // exercise the race recovery branch.
      const mbid = `${PREFIX}-race-mb`;
      const [a, b] = await Promise.all([
        matchOrCreatePerformer({
          name: `${PREFIX} Race MB A`,
          musicbrainzId: mbid,
        }),
        matchOrCreatePerformer({
          name: `${PREFIX} Race MB B`,
          musicbrainzId: mbid,
        }),
      ]);
      assert.equal(a.performer.id, b.performer.id);
      assert.equal(a.performer.musicbrainzId, mbid);
      const rows = await db
        .select()
        .from(performers)
        .where(eq(performers.musicbrainzId, mbid));
      assert.equal(rows.length, 1);
    });
  });
});
