// Payloads for the three Artist page variants.
// Mirrors show-detail-data conventions: kindKey drives layout; auto-fetched fields marked.

window.ARTIST_PAYLOADS = {
  concert: {
    kindKey: 'concert',
    kind: 'concert',
    name: 'Fontaines D.C.',
    tagline: 'post-punk · Dublin · est. 2017',
    bio: 'Irish post-punk five-piece from Dublin. Four LPs since 2019; "Romance" (2024) is the current tour.',
    stats: [
      ['seen live',    '3',   'since Jun 2022'],
      ['songs heard',  '47',  'of ~82 catalog'],
      ['tours',        '4',   'tracked'],
      ['cities',       '2',   'NY · Brooklyn'],
      ['first show',   '22',  'Brooklyn Steel'],
    ],
    shows: [
      { d:'APR 04 · 26', v:'Kings Theatre',   city:'Brooklyn',   tour:'Romance Tour',          songs:16, cur:true },
      { d:'OCT 11 · 24', v:'Terminal 5',      city:'Manhattan',  tour:'Skinty Fia',            songs:15 },
      { d:'JUN 22 · 22', v:'Brooklyn Steel',  city:'Brooklyn',   tour:'(supporting IDLES)',    songs:8 },
    ],
    upcoming: {
      d:'JUL 28 · 26', v:'Kilmainham', city:'Dublin IE',
      note:'not ticketed yet · notify when on sale',
    },
    cities: [
      { label:'Brooklyn · 2', x:58, y:62, r:14 },
      { label:'Manhattan · 1', x:52, y:48, r:9 },
    ],
    songs: [
      ['Boys in the Better Land', false],
      ['Big Shot', true],
      ['Starburster', false],
      ['Favourite', true],
      ['Romance', false],
      ['Nabokov', false],
      ['Bug', false],
      ['Jackie Down the Line', false],
      ['I Love You', false],
      ['In the Modern World', false],
      ["A Hero's Death", true],
      ["Here's the Thing", true],
      ['Televised Mind', false],
      ['Too Real', false],
    ],
    songsMeta: '14 of 47 · ◆ first-time-live',
    related: ['IDLES','Shame','Dry Cleaning','The Murder Capital','Been Stellar','Squid'],
    discography: [
      { y:'2024', t:'Romance',        you:true,  note:'current tour' },
      { y:'2022', t:'Skinty Fia',     you:true },
      { y:'2020', t:"A Hero's Death", you:false },
      { y:'2019', t:'Dogrel',         you:false },
    ],
  },

  comedy: {
    kindKey: 'comedy',
    kind: 'comedy',
    name: 'John Mulaney',
    tagline: 'stand-up · sack lunch bunch era',
    bio: 'American comedian. Five Netflix specials since 2012; currently on the 48-city "All Is Forgiven" run.',
    stats: [
      ['seen live',    '3',   'since Feb 2019'],
      ['tours',        '2',   'tracked'],
      ['specials',     '5',   'released'],
      ['specials saw', '2',   'of 5 live'],
      ['first show',   '19',  'Chicago Theatre'],
    ],
    shows: [
      { d:'FEB 14 · 26', v:'Beacon Theatre',   city:'New York',  tour:'"All Is Forgiven"',  ctx:'new material · pre-special', cur:true },
      { d:'MAR 09 · 23', v:'Radio City',       city:'New York',  tour:'"From Scratch"',     ctx:'became the Netflix special' },
      { d:'OCT 22 · 19', v:'Chicago Theatre',  city:'Chicago',   tour:'"Kid Gorgeous" run', ctx:'last tour pre-rehab' },
    ],
    upcoming: {
      d:'OCT 04 · 26', v:'Madison Square Garden', city:'New York NY',
      note:'2 nights · on sale now',
    },
    upcomingExtra: [
      { d:'NOV 12 · 26', v:'Chicago Theatre', note:'6-night run' },
      { d:'DEC 02 · 26', v:'Kia Forum',       note:'Los Angeles CA' },
    ],
    // specials you've seen become…
    specials: [
      { t:'All Is Forgiven',  net:'touring',  yr:'2026', saw:'saw live · tonight',  mine:true },
      { t:'Baby J',           net:'Netflix',  yr:'2023', saw:null },
      { t:'From Scratch',     net:'Netflix',  yr:'2022', saw:'saw the tour · 2023', mine:true },
      { t:'Kid Gorgeous',     net:'Netflix',  yr:'2018', saw:'saw the tour · 2019', mine:true },
      { t:'The Comeback Kid', net:'Netflix',  yr:'2015', saw:null },
      { t:'New in Town',      net:'Comedy Central', yr:'2012', saw:null },
    ],
    timeline: [
      { y:'2026', t:'All Is Forgiven',        you:true,  note:'touring now' },
      { y:'2023', t:'Baby J (Netflix)',       you:false },
      { y:'2022', t:'From Scratch tour',      you:true },
      { y:'2018', t:'Kid Gorgeous (Netflix)', you:true },
      { y:'2015', t:'The Comeback Kid',       you:false },
      { y:'2012', t:'New in Town',            you:false },
    ],
    related: ['Nick Kroll','Pete Davidson','Sarah Silverman','Marcello Hernández','Seth Meyers'],
  },

  theatre: {
    kindKey: 'theatre',
    kind: 'theatre · musical',
    name: 'Hadestown',
    tagline: 'by Anaïs Mitchell · 2019 premiere · running',
    bio: 'Anaïs Mitchell\'s folk-opera retelling of Orpheus & Eurydice. Opened on Broadway at the Walter Kerr in 2019; won 8 Tonys incl. Best Musical.',
    stats: [
      ['seen',       '2',       'since Nov 2022'],
      ['tony wins',  '8',       'incl. Best Musical'],
      ['opened',     '2019',    'Walter Kerr'],
      ['home',       'W. Kerr', '48th St'],
      ['perf. #',    '2,100',   'at your last visit'],
    ],
    visits: [
      {
        d:'MAR 22 · 26',
        theatre:'Walter Kerr',
        seat:'Orch · Row M · 14',
        cast:[['Orpheus','Jordan Fisher'],['Eurydice','Phillipa Soo'],['Hades','Phillip Boykin'],['Persephone','Lillias White']],
        cur:true,
      },
      {
        d:'NOV 09 · 22',
        theatre:'Walter Kerr',
        seat:'Mezz · Row B · 8',
        cast:[['Orpheus','Reeve Carney'],['Eurydice','Solea Pfeiffer'],['Hades','Patrick Page'],['Persephone','Amber Gray']],
      },
    ],
    credits: [
      ['book',     'Anaïs Mitchell'],
      ['music',    'Anaïs Mitchell'],
      ['director', 'Rachel Chavkin'],
      ['choreo',   'David Neumann'],
      ['scenic',   'Rachel Hauck'],
    ],
    running: {
      theatre:'Walter Kerr Theatre · 48th St',
      schedule:'Tue–Sun · open run · no scheduled close',
      actions:['book a return →','lottery','rush'],
    },
    productionTimeline: [
      { y:'2026', t:'Post-Tony revival cast',     you:false },
      { y:'2022', t:'You saw it · tour cast',     you:true },
      { y:'2019', t:'Broadway premiere · 8 Tonys',you:false },
      { y:'2017', t:'Off-Broadway · NYTW',        you:false },
      { y:'2016', t:'Edmonton workshop run',      you:false },
    ],
    songs: [
      ['Road to Hell',                 false],
      ['Any Way the Wind Blows',       false],
      ['Come Home with Me',            true],
      ['Wedding Song',                 false],
      ['Epic I',                       true],
      ['Way Down Hadestown',           false],
      ['Hey, Little Songbird',         false],
      ['When the Chips are Down',      false],
      ['Chant',                        false],
      ['Wait for Me',                  true],
      ['Our Lady of the Underground',  false],
      ['Flowers',                      false],
    ],
    songsMeta: '12 of 30 · ◆ new to you this visit',
    related: ['Natasha, Pierre & The Great Comet','The Band\'s Visit','Once','Spring Awakening'],
  },
};
