/**
 * Single source of truth for the launch-splash logo size.
 *
 * The cold-launch splash is painted twice in sequence: first the OS-level
 * *native* splash (generated by `expo-splash-screen` from app.config.ts),
 * then the JS `<BrandSplash/>` (components/BrandSplash.tsx) once React Native
 * has mounted. For the handoff to be invisible (no "size pop"), BOTH must
 * render `assets/splash.png` at the *same* centered size.
 *
 * expo-splash-screen's iOS storyboard lays the image into an
 * `imageWidth × imageWidth` square box with `scaleAspectFit`, centered (see
 * `expo-splash-screen/plugin/build/InterfaceBuilder.js` → `width/height =
 * imageWidth`). `<BrandSplash/>` mirrors that exactly with a square
 * `SPLASH_IMAGE_WIDTH × SPLASH_IMAGE_WIDTH` box + `resizeMode="contain"`.
 *
 * `<BrandSplash/>` imports this constant directly. `app.config.ts` can't —
 * the Expo config loader compiles app.config.ts in isolation and doesn't
 * resolve transitive `.ts` imports — so it carries a hand-kept `imageWidth`
 * literal whose equality with this value is asserted by
 * `lib/__tests__/splash.test.ts`. That test is the guard: the two sizes
 * drifted before (native default 100 vs a full-size JS splash) and produced
 * exactly the "tiny icon → normal icon" pop this coupling exists to prevent.
 *
 * Keep this file dependency-free (no React Native / Expo imports) so the test
 * and BrandSplash can both load it cheaply.
 */
export const SPLASH_IMAGE_WIDTH = 200;
