/**
 * Single source of truth for the launch-splash logo size.
 *
 * The cold-launch splash is painted twice in sequence: first the OS-level
 * *native* splash (generated by `expo-splash-screen` from app.config.ts),
 * then the JS `<BrandSplash/>` (components/BrandSplash.tsx) once React Native
 * has mounted. The handoff differs per platform:
 *
 * iOS — the storyboard lays `assets/splash.png` into an
 * `imageWidth × imageWidth` square box with `scaleAspectFit`, centered (see
 * `expo-splash-screen/plugin/build/InterfaceBuilder.js` → `width/height =
 * imageWidth`). `<BrandSplash/>` mirrors that exactly with a square
 * `SPLASH_IMAGE_WIDTH × SPLASH_IMAGE_WIDTH` box + `resizeMode="contain"`, so
 * the native→JS transition is invisible.
 *
 * Android — the Android 12+ system splash ignores `imageWidth` and renders the
 * splash drawable circle-masked at the fixed OS icon size, always smaller than
 * this box. No size can make it match, so the native splash carries a fully
 * transparent image (`assets/splash-blank.png`) and the first visible mark is
 * the JS `<BrandSplash/>`: plain #0C0C0C → correctly-sized logo, no pop.
 *
 * `<BrandSplash/>` imports this constant directly. `app.config.ts` can't —
 * the Expo config loader compiles app.config.ts in isolation and doesn't
 * resolve transitive `.ts` imports — so it carries a hand-kept `imageWidth`
 * literal whose equality with this value is asserted by
 * `lib/__tests__/splash.test.ts`. That test also pins the Android blank-image
 * override: both halves have regressed before (native default 100 vs a
 * full-size JS splash in the early builds; the Android logo restored by #539's
 * build fix) and each produced exactly the "small icon → normal icon" pop this
 * coupling exists to prevent.
 *
 * Keep this file dependency-free (no React Native / Expo imports) so the test
 * and BrandSplash can both load it cheaply.
 */
export const SPLASH_IMAGE_WIDTH = 200;
