// Payloads for the three show-detail variants.
// Auto-fetched fields are clearly modeled; the user never types them.

window.SD_PAYLOADS = {
  concert: {
    kindKey: 'concert',
    kind: 'concert',
    headliner: 'Fontaines D.C.',
    support: 'Been Stellar',
    supportPrefix: 'with',
    date: { d: '04', m: 'APR', y: '2026', dow: 'SATURDAY' },
    time: 'doors 7:00 pm · show 8:00 pm',
    venue: 'Kings Theatre',
    neighborhood: 'Flatbush · Brooklyn',
    tour: 'Romance World Tour',
    paid: '78.00',
    source: 'Ticketmaster',
    seenOrdinal: '3rd time',
    seenCount: 3,
    facts: [
      ['venue',  'Kings Theatre'],
      ['where',  'Flatbush · Brooklyn'],
      ['seat',   'Orchestra · Row M · Seat 14'],
      ['tour',   'Romance World Tour'],
      ['paid',   '$78.00', null, 'via Ticketmaster'],
    ],
    lineup: [
      { role: 'headliner', name: 'Fontaines D.C.', detail: '16 songs · 72 min', seen: '3rd' },
      { role: 'support',   name: 'Been Stellar',   detail: '8 songs · 35 min',  seen: '1st' },
    ],
    setlist: [
      ['Romance', false, '3:42'], ['Starburster', false, '3:28'], ["Here's the Thing", true, '2:56'],
      ['Jackie Down the Line', false, '3:50'], ['In the Modern World', false, '4:12'], ['Favourite', true, '3:18'],
      ['Nabokov', false, '4:05'], ['Bug', false, '3:04'], ['I Love You', false, '5:10'],
    ],
    encore: [
      ['Big Shot', true, '3:22'], ['Boys in the Better Land', false, '3:36'], ["A Hero's Death", true, '4:44'],
    ],
    setlistNote: '4 first-time-live · 47 unique Fontaines songs across 3 shows',
    stats: [
      ['show no.',     '3rd',  'with Fontaines · since 2022'],
      ['run-time',     '72m',  '16 songs · 4:30 avg'],
      ['new songs',    '4',    'from 12 played'],
      ['at venue',     '12',   'since 2019'],
      ['lifetime',     '184',  'shows tracked'],
    ],
    notes: 'Kings Theatre sounded cavernous on the low end; Grian lost his voice on Favourite and the crowd carried the chorus — still my best Fontaines show of the three.',
    withArtistTitle: 'With Fontaines D.C.',
    withArtist: [
      { d: 'APR 04 · 26', v: 'Kings Theatre',   sub: 'Brooklyn', cur: true },
      { d: 'OCT 11 · 24', v: 'Terminal 5',      sub: 'Manhattan' },
      { d: 'JUN 22 · 22', v: 'Brooklyn Steel',  sub: 'Brooklyn' },
    ],
    atVenueTitle: 'At Kings Theatre',
    atVenueMeta: '12 visits',
    atVenueMore: '+ 8 earlier',
    atVenue: [
      ['APR 04 · 26', 'Fontaines D.C.', true],
      ['OCT 11 · 25', 'Japanese Breakfast'],
      ['JUN 02 · 25', 'Alvvays'],
      ['OCT 14 · 24', 'Big Thief'],
    ],
  },

  comedy: {
    kindKey: 'comedy',
    kind: 'comedy',
    headliner: 'John Mulaney',
    subtitle: '"All Is Forgiven"',
    subtitleItalic: true,
    date: { d: '14', m: 'FEB', y: '2026', dow: 'SATURDAY' },
    time: '8:00 pm',
    venue: 'Beacon Theatre',
    neighborhood: 'Upper West Side',
    tour: '"All Is Forgiven" · 48-city run',
    paid: '95.00',
    source: 'Ticketmaster',
    seenOrdinal: '3rd time',
    facts: [
      ['venue',  'Beacon Theatre'],
      ['where',  'Upper West Side'],
      ['seat',   'Mezzanine · Row C · Seat 22'],
      ['tour',   '"All Is Forgiven" · 48-city'],
      ['paid',   '$95.00', null, 'via Ticketmaster'],
    ],
    lineupTitle: 'Opener · 1',
    lineupMeta: 'no setlist for comedy',
    lineup: [
      { role: 'headliner', name: 'John Mulaney', detail: 'pre-special tour · 90 min', seen: '3rd' },
      { role: 'opener',    name: 'Marcello Hernández', detail: '15 min · now tracked', seen: '1st' },
    ],
    materialContext: "Pre-special material. Mulaney's tours typically become a Netflix release 12–18 months after the run wraps — this is his first tour since \"Baby J\" (2023).",
    materialMeta: 'likely special: late 2026 / early 2027',
    withArtistTitle: 'With Mulaney',
    withArtist: [
      { d: 'FEB 14 · 26', v: 'Beacon Theatre',     sub: '"All Is Forgiven"', cur: true },
      { d: 'NOV 08 · 22', v: 'Radio City',         sub: '"From Scratch"' },
      { d: 'MAR 15 · 19', v: 'Chicago Theatre',    sub: '"Kid Gorgeous"' },
    ],
    atVenueTitle: 'At Beacon',
    atVenueMeta: '6 visits',
    atVenueMore: '+ 2 earlier',
    atVenue: [
      ['FEB 14 · 26', 'John Mulaney', true],
      ['JUL 22 · 25', 'Iliza Shlesinger'],
      ['MAR 08 · 25', 'Matt Rife'],
      ['NOV 12 · 24', 'Sarah Silverman'],
    ],
    stats: [
      ['show no.',    '3rd',  'with Mulaney · since 2019'],
      ['run-time',    '90m',  'plus 15m opener'],
      ['tour length', '48',   'cities on this run'],
      ['at venue',    '6',    'since 2021'],
      ['lifetime',    '184',  'shows tracked'],
    ],
    specials: [
      { t: 'Kid Gorgeous',   net: 'Netflix · 2018', saw: 'saw live · 2019' },
      { t: 'From Scratch',   net: 'Netflix · 2022', saw: 'saw live · 2022' },
      { t: 'Baby J',         net: 'Netflix · 2023', saw: null },
      { t: 'All Is Forgiven',net: 'touring · 2026', saw: 'saw live · tonight' },
    ],
    notes: 'Tighter than "From Scratch" — less sprawl, sharper callbacks. Marcello Hernández is electric as opener; add him as a tracked artist.',
  },

  theatre: {
    kindKey: 'theatre',
    kind: 'theatre',
    headliner: 'Hadestown',
    subtitle: 'Broadway · 2,100th performance',
    date: { d: '22', m: 'MAR', y: '2026', dow: 'SUNDAY' },
    time: '3:00 pm matinée',
    venue: 'Walter Kerr Theatre',
    neighborhood: 'West 48th · Midtown',
    tour: 'Broadway · open run since 2019',
    paid: '148.00',
    source: 'Telecharge',
    seenOrdinal: '2nd time',
    facts: [
      ['theatre', 'Walter Kerr Theatre'],
      ['where',   'West 48th · Midtown'],
      ['seat',    'Orchestra · Row M · Seat 14'],
      ['run',     'Broadway · open run since 2019'],
      ['paid',    '$148.00', null, 'via Telecharge'],
    ],
    cast: [
      ['Orpheus',     'Jordan Fisher',  true],
      ['Eurydice',    'Phillipa Soo'],
      ['Hades',       'Phillip Boykin'],
      ['Persephone',  'Lillias White',  true],
      ['Hermes',      'Reeve Carney'],
      ['Fates',       'Afton · Odorisio · Moyano'],
    ],
    castNote: 'auto-captured for your exact date · never edit manually',
    withArtistTitle: 'Your Hadestown history',
    withArtist: [
      { d: 'MAR 22 · 26', v: 'Walter Kerr',    sub: 'Fisher / Soo / Boykin', cur: true },
      { d: 'NOV 09 · 22', v: 'Walter Kerr',    sub: 'Carney / Pfeiffer / Page' },
    ],
    atVenueTitle: 'At Walter Kerr',
    atVenueMeta: '3 visits',
    atVenueMore: '+ 1 earlier',
    atVenue: [
      ['MAR 22 · 26', 'Hadestown', true],
      ['NOV 09 · 22', 'Hadestown'],
      ['FEB 14 · 20', 'Six'],
    ],
    stats: [
      ['show no.',    '2nd',  'Hadestown · since 2022'],
      ['run-time',    '2h 30m', 'incl. 15m intermission'],
      ['cast subs',   '2',    'of 6 principals'],
      ['at venue',    '3',    'since 2020'],
      ['lifetime',    '184',  'shows tracked'],
    ],
    notes: 'Jordan Fisher is a softer Orpheus than Carney — more boyish, less feral. Lillias White still owns "Our Lady of the Underground". Worth the revisit.',
  },
};
